version: "3.8"

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=apptuongtac
      - MYSQL_ROOT_HOST=%
    healthcheck:
      test: mysql apptuongtac --user=root --password='root' --silent --execute "SELECT 1;"
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
      - ./app.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - spring-net
  app:
    depends_on:
      mysql:
       condition: service_healthy
    build: .
    restart: on-failure
    ports:
      - "8081:8080"
    networks:
      - spring-net
volumes:
  db:
networks:
  spring-net:
    driver: bridge

