package com.vn.bkfet.enums;

public enum District {
    BADINH, HOANKIEM, TAYHO, LONGBIEN, CAUGIAY, DONGDA, HAIBATRUNG, HOANGMAI, THANHXUAN, NAMTULIEM, BACTULIEM, HADONG, SONTAY, BAVI, CHUONGMY, DANPHUONG, HOAIDUC, MYDUC, PHUXUYEN, PHUCTHO, QUOCOAI, THACHTHAT, THANHOAI, THANHTRI, UNGHOA

}
